# Generated by Django 3.2.4 on 2021-08-05 09:07

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_date', models.DateField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('access1', models.CharField(max_length=60)),
                ('access2', models.CharField(max_length=60)),
                ('access3', models.CharField(max_length=60)),
                ('age', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('fee', models.CharField(max_length=10)),
                ('after_fee', models.CharField(max_length=10)),
                ('before_fee', models.CharField(max_length=10)),
                ('madori', models.CharField(max_length=10)),
                ('menseki', models.CharField(max_length=10)),
                ('detail', models.URLField()),
                ('createted_at', models.DateTimeField()),
                ('realprice', models.IntegerField()),
                ('pred', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('pred_price', models.IntegerField()),
                ('pred_fee', models.IntegerField()),
                ('pred_before_fee', models.IntegerField()),
                ('pred_after_fee', models.IntegerField()),
                ('difference_normalize', models.FloatField()),
                ('value_rate', models.FloatField()),
                ('like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
