# Generated by Django 3.2.4 on 2021-07-08 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
    ]
