# Generated by Django 3.2.4 on 2021-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210615_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(default='sample', max_length=254)),
                ('area', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=254)),
                ('price', models.CharField(max_length=10)),
                ('fee', models.CharField(max_length=10)),
                ('after_fee', models.CharField(max_length=10)),
                ('before_fee', models.CharField(max_length=10)),
                ('madori', models.CharField(max_length=10)),
                ('menseki', models.CharField(max_length=10)),
                ('access1', models.CharField(max_length=100)),
                ('access2', models.CharField(max_length=100)),
                ('access3', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('detail_url', models.URLField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(blank=True, to='app.Property'),
        ),
    ]
