# Generated by Django 3.2.4 on 2021-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210709_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='access1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='access2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='access3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='sample', max_length=50),
        ),
    ]
